version: 2
updates:
  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: typescript
        versions:
          - '>=7.0.0'

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: typescript
        versions:
          - '>=7.0.0'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - '*'
